//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public int idGenre { get; set; }
        public int idPublishing { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Publishing Publishing { get; set; }
    }
}
