//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publishing
    {
        public Publishing()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int year { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
