//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atm
    {
        public Atm()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string phone { get; set; }
        public string addressatm { get; set; }
        public bool mainoffice { get; set; }
        public double gpsX { get; set; }
        public double gpsY { get; set; }
        public int timeopen { get; set; }
        public int timeclose { get; set; }
        public System.DateTime dateregister { get; set; }
        public string cashier { get; set; }
        public string description { get; set; }
        public int idbank { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
