//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Atm = new HashSet<Atm>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime datekurs { get; set; }
        public int time { get; set; }
        public double usdsell { get; set; }
        public double usdbuy { get; set; }
        public double eursell { get; set; }
        public double eurbuy { get; set; }
        public double rursell { get; set; }
        public double rurbuy { get; set; }
        public int idparsebank { get; set; }
    
        public virtual ICollection<Atm> Atm { get; set; }
    }
}
