//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Atm = new HashSet<Atm>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int code { get; set; }
    
        public virtual ICollection<Atm> Atm { get; set; }
    }
}
